#!/usr/bin/env python3

import rosbag
import statistics
#import numpy as np

x = []
y = []
z = []

bag = rosbag.Bag('/home/rosmatch/catkin_ws_yassin/src/match/my_scripts/recording/30_sec_static.bag')

for topic, msg, t in bag.read_messages(topics=['/position_marvelmind']):
    
    x.append(msg.pose.position.x)
    y.append(msg.pose.position.y)
    z.append(msg.pose.position.z)

bag.close()

variance_x = statistics.variance(x)
variance_y = statistics.variance(y)
variance_z = statistics.variance(z)
print(variance_x, variance_y, variance_z)